### ISSUE TITLE
One of your mods may be making it impossible to craft some vanilla items.

### ISSUE THREAD

**Issue by CsillaAria** [Stein-N/Resource-Backpacks#1]
When I added this mod, along with the library, and config I was unable to make a crafting table, and some vanilla items. I'm not sure if it's just your mods causing it, or if there is some issue from another mod, but removing your mods fixed the problem. 

NeoForge version 21.0.61

Mod versions: 
resource_backpacks-neoforge-0.5.4-BETA.jar
resourcelibrary-neoforge-1.21-2.0.0.jar
resourceconfigapi-neoforge-1.21-2.0.0.jar

My latest log if that will help: https://bytebin.lucko.me/nYYMxLPu3a

I don't understand modding at all, so I don't know if I can be of any more assistance, but if you need something else from me I'll do my best.

**Comment by Stein-N** [comment]
Can you zip your complete instance and upload it to file.io and post the link?
Then I can have a better look.

But what I can say now is that only Resource Backpacks provide recipes.

**Comment by CsillaAria** [comment]
https://file.io/VlhvJkaZ1GjM

I hope I did this right and it helps.

**Comment by Stein-N** [comment]
I mean the whole .minecraft folder with all mods and configs. When you are using the prism launcher or curse forge you can export the profile.

**Comment by CsillaAria** [comment]
Ok, sorry about that. 

https://file.io/VVo1sUVD9sY2

**Comment by Stein-N** [comment]
sry didn't meant to be rude, thanks will have a look into it

**Comment by Stein-N** [comment]
OK nice the upload already go tdeleted, can you upload it again pls :/

**Comment by Stein-N** [comment]
ok found the issue, you dont need to upload your instance again

**Comment by Stein-N** [comment]
New version is available on Curseforge but needs to be approved

**Comment by CsillaAria** [comment]
Everything is working again! Thank you so much!

**Comment by Stein-N** [comment]
Thank you for reporting the issue :)
