### ISSUE TITLE
Loot Table Collision

### ISSUE THREAD

**Issue by mandychuu** [Stein-N/Resource-Backpacks#13]
When you equip the Backpack into the "accessories" slot, it causes all mobs to stop dropping items and XP. When the Backpack is removed from the "accessories" slot, items and XP begins to drop once again.

**Comment by Stein-N** [comment]
Hey sry for the late response, i couldn't find any reason for this issue. Resource Backpacks isn't adding any loottable only item and entity Tags so that Accessories/Trinkets/Curios API can add them to the correct Slots.

**Comment by Stein-N** [comment]
with version 0.9.0-BETA all compatibility with any Trinket API is removed, so there should be no longer an issue.
