### ISSUE TITLE
Server Not Launching

### ISSUE THREAD

**Issue by TallHats96** [Stein-N/Resource-Backpacks#2]
im trying to launch a dedicated server for my own modpack and specificaly this mod's v0.5.3-BETA update is preventing my server from launching, i got a screenshot of the last chunk of script from the server window.
![image](https://github.com/Stein-N/Resource-Backpacks/assets/79264981/b72643fb-e241-4bfc-ab83-9036d1d19170)

**Comment by Stein-N** [comment]
Thanks for reporting the issue, found the issue. I will publish a fix later that day.

**Comment by ayrus02** [comment]
Yeah, I've also found the same problem for my private server, I've also tried these versions: 

resource_backpacks-fabric-0.5.5-BETA (failed to launch the server)
resource_backpacks-fabric-0.5.4-BETA (was unable to launch the server)
resource_backpacks-fabric-0.5.3-BETA (was unable to launch the server)
resource_backpacks-fabric-0.5.1-BETA (successfully launching the server)

Below are screenshot of the server startup log

![image](https://github.com/Stein-N/Resource-Backpacks/assets/34953163/df491792-8611-4ffe-bb48-a8c0b861f397)

Regards,
ayrus02

**Comment by Stein-N** [comment]
New Version is available on Modrinth and on Curseforge it needs to be approved

**Comment by ayrus02** [comment]
Hi, @Stein-N, thanks for the update, I can confirm that the newest version resource_backpacks-fabric-0.5.6-BETA.jar can be run in my private server.

Regards,
ayrus02
