### ISSUE TITLE
Unable to open backpack from Inventory with keybind (open_from_inventory = true)

### ISSUE THREAD

**Issue by Tursiops-G** [Stein-N/Resource-Backpacks#24]
### Mod loader

Forge

### Mod version

forge-1.21.3-0.10.1-BETA

### Minecraft version

1.21.3

### Issue description

Unable to open backpack from inventory (with "B" keybind). 
Opens If right-clicked from Toolbar (in free air, otherwise gets placed) or if held in off-hand, But will close ok with "B" keybind.
(open_from_inventory = true set in resource_backpacks.toml).
(No other keybinds conflicting with "B").
No apparent log errors.
Forge 53.0.25

### If Bug

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Provide the latest.log file

N/A

**Comment by Stein-N** [comment]
Hey this is normal and intentional behavior, the Backpack only opens via KeyBind when equipped in the Chest slot. otherwise you have to hold it in your hand to open is.
