### ISSUE TITLE
how to craft first Backpack? 1.21.3

### ISSUE THREAD

**Issue by Red05Wins** [Stein-N/Resource-Backpacks#26]
### Mod loader

Fabric

### Mod version

last version

### Minecraft version

1.21.3

### Issue description

how to craft first Backpack? 1.21.3 i am using feather

### If Bug

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

**Comment by Stein-N** [comment]
Here are the Recipes for all Backpacks, i recommend to use EMI, Just Enough Items or Roughly Enough Items as a recipe viewer mod:

Leather:
You can use normal Leather and Rabbit Hide
![backpack_leather](https://github.com/user-attachments/assets/a9847912-7dc7-4828-8c62-a3f52795b35f)

Copper:
![backpack_copper](https://github.com/user-attachments/assets/a44a6d6b-e0b9-4a86-9d7a-8a50ff351c04)

Gold:
![backpack_gold](https://github.com/user-attachments/assets/d80834bf-797b-436d-bd35-55f10bf827c4)

Iron:
![backpack_iron](https://github.com/user-attachments/assets/3b941a9b-8e50-49c3-836c-1a4b8a4807c4)

Diamond:
![backpack_diamond](https://github.com/user-attachments/assets/ba9d400a-180f-4ef3-8638-466afd6cc6bf)

Netherite:
![backpack_netherite](https://github.com/user-attachments/assets/dcd2ecb5-71e2-45ff-ae54-ad65bfc1fd65)

End:
![backpack_end](https://github.com/user-attachments/assets/ed059be9-a95d-40a8-a996-ea2db104f66b)
