### ISSUE TITLE
Resource-Backpacks v0.5.6-BETA cannot load after update Resource-Library to version v2.0.2

### ISSUE THREAD

**Issue by ayrus02** [Stein-N/Resource-Backpacks#3]
Hi @Stein-N, I've encountered this problem while running the Minecraft Client after updating Resource-Library to version **resourcelibrary-fabric-1.21-2.0.2.jar** 

![image](https://github.com/Stein-N/Resource-Backpacks/assets/34953163/59f62421-1f83-44b9-866a-a2a0bb034bff)

The Resource-Backpacks version is **resource_backpacks-fabric-0.5.6-BETA.jar**
Please update the Resource-Backpacks mod to be able to use this version of Resource-Library.

Regards,
ayrus02

**Comment by Stein-N** [comment]
my bad, the new Resource Backpack version will be available in 10-15 minutes sorry for the issue

**Comment by Stein-N** [comment]
New version is available on Modrinth
