### ISSUE TITLE
Possible compatibility issue

### ISSUE THREAD

**Issue by BlocksRock-1006** [Stein-N/Resource-Backpacks#30]
### Mod loader

Fabric

### Mod version

0.10.4

### Minecraft version

1.21.4

### Issue description

It seems that with Resource Backpacks installed, searching in the recipe book causes a crash, with the logs pointing to RB causing some render thread related issue. It seems to only happen when I launch the game, load into a world, close the game completely, then relaunch and open the same world. Unfortunately I cannot reproduce the bug with your mod (plus dependencies) alone, but I've no idea what sort of compat issue could be causing it. Can confirm, adding your mod to my existing pack causes crashes though.

### If Bug

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Provide the latest.log file

https://gist.github.com/BlocksRock-1006/215519f73b3788dac5ca4b90b7627d08

**Comment by Stein-N** [comment]
Might be an issue with axiom installed alongside resource Backpacks, i will have a look at it.
Could you try it again without axiom installed

**Comment by BlocksRock-1006** [comment]
Have tried with Axiom disabled, trying now with it fully uninstalled

**Comment by BlocksRock-1006** [comment]
Alright, new issue (sorta). Trying to search in the recipe book before the world loads in causes the "network error" message, then kicks me out to the server list. reloading the world, waiting for chunks to load, then trying again causes the same crash from before. New log as follows:
https://gist.github.com/BlocksRock-1006/2e11b02ded1643d596a9818a4e398cb7
Don't mind the world name, just tried to put the most random thing I could think of

Edit: should mention, this is an integrated singleplayer server, so kicking me out to the multiplayer server select is odd.

**Comment by Stein-N** [comment]
Dumb question but how can you search in the recipe book before the world loads?

**Comment by BlocksRock-1006** [comment]
I meant I log out in the same chunk as a crafting table, then open the world and the table before the other chunks actually appear.

**Comment by BlocksRock-1006** [comment]
like the world is running, but before chunks load in fully.

**Comment by Stein-N** [comment]
ahh ok, then i missunderstood it

**Comment by Stein-N** [comment]
What Launcher do u use?

When you use prism launcher, can you please export your instance as a curseforge or modrinth pack please

**Comment by BlocksRock-1006** [comment]
Modrinth Launcher
https://file.io/nIUprIdJ51X6 is the instance with everything relevant included
[my instance 2 1.0.0.zip](https://github.com/user-attachments/files/18156012/my.instance.2.1.0.0.zip)
is the instance renamed to a zip for GitHub with only the mods/respacks/shaderpacks/configs to reduce filesize

**Comment by Stein-N** [comment]
So i tested your instance with the following steps:

1. Create a new world
  - searching works and no disconnects/crashes
 2. leave the world and close the game completely
 3. restart the game and join the world
 4. search in the recipe book
   - still no crash or disconnect
   
These are the steps i get from your initial report, please try again but before that wipe all your config files or create a new instance with the my instance 2 1.0.0.zip file and try if the disconnect/crash still happens

**Comment by BlocksRock-1006** [comment]
Ok, not a compat issue (I guess), I think it has to do with editing the keybinds.
I unbound the "Compact Preview" key and changed "Full Preview" to left Shift, leaving the open backpack keybind alone ('B')
THAT would explain the error log saying something about hasShiftDown

**Comment by BlocksRock-1006** [comment]
That lets me reproduce the issue, even on a clean options.txt

**Comment by Stein-N** [comment]
Ahh ok, then the fix should be relatively easy, the current state is that both keys have to be bound and at first you have to press the compact preview and then the full inventory keybind.

I will implement a better check tomorrow.

**Comment by Stein-N** [comment]
Hey i uploaded a snapshot of the new version, would you like to test if you can reproduce the crash/disconnect with this version.

https://raw.githubusercontent.com/Stein-N/resources/main/snapshots/resource_backpacks/resource_backpacks-fabric-1.21.4-0.10.6-BETA.jar

**Comment by BlocksRock-1006** [comment]
Can confirm, crash no longer occurs with this linked version.

**Comment by Stein-N** [comment]
ok nice thanks for testing :)
