### ISSUE TITLE
Cannot craft new backpack since version v0.5.7-BETA wether on Singleplayer mode or Multiplayer Mode

### ISSUE THREAD

**Issue by ayrus02** [Stein-N/Resource-Backpacks#5]
Hi @Stein-N,

Today I created a new world with the latest version of Resource Backpacks v0.6.0-BETA
But I cannot craft the leather backpack, when I look at JEI for the recipe, there is no recipe that I can use to craft the backpack.

Below is the recipe I used on version v0.5.6-BETA and Resource-Library v2.0.0 but since version v0.5.7-BETA and using Resource-Library v2.0.2 I cannot craft it anymore.
![image](https://github.com/Stein-N/Resource-Backpacks/assets/34953163/d1ac06c5-ecc7-41ff-89cc-f3d996e08c6d)

Below is when I tried to craft the recipe with version v0.6.0-BETA and Resource-Library v2.0.2
![image](https://github.com/Stein-N/Resource-Backpacks/assets/34953163/bd160f44-36cd-450f-8597-748351138aba)

But when I load the other world that has Resource Backpacks already crafted in inventory, it can function as expected.
I don't know if it is caused by the updated Resource-Library from v2.0.0 to v2.0.2 or because of the Resource-Backpacks updated from v0.5.6-BETA to v0.5.7-BETA.

Hope you can found the root cause of this problem and fix it. Thanks for you time and effort in creating this mods.

Regards,
ayrus02

**Comment by Stein-N** [comment]
New version is available
