### ISSUE TITLE
Cannot Access the Resource-Backpacks thru KeyBind on v0.6.1-BETA

### ISSUE THREAD

**Issue by ayrus02** [Stein-N/Resource-Backpacks#6]
Hi @Stein-N, 

I've upgraded the Resource-Backpacks with v0.6.1-BETA, but when I try to open the backpack using KeyBind, I cannot opened it. 
I've tried it using Multiplayer Mode, tried to put the backpacks in inventory or the hotbar, and it still cannot be opened.
I've also tried to change the KeyBind and still cannot open the backpack using new KeyBind.

Regards,
ayrus02

**Comment by Stein-N** [comment]
Backpacks can no longer be opened via Key bind when they are in your Inventory or Hotbar. Equip it in the Back Slot of Accessories or Curios API and the Key bind will work.
When Accessories, Curios API or later Trinkets aren't installed you can equip the back pack in the Chest plate Slot.

On Testing all Slots where working with the KeyBind, when you have further issues please let me know.

**Comment by ayrus02** [comment]
Okay, but the Curios API or Trinkets are not available yet for Minecraft v1.21. So the only option is to equip the backpack to the back slot right?

![image](https://github.com/user-attachments/assets/1eab4c7c-1a77-410e-a08d-458597150c2d)

I've tried to equip the backpack to chest plate slot but it still cannot be opened with the KeyBind.

Please can you put back the KeyBind for Minecraft v1.21 if the Backpack are in inventory or hotbar.

Regards,
ayrus02

**Comment by Stein-N** [comment]
[Accessories](https://modrinth.com/mod/accessories) is already available for 1.21 that has the same functionality like Trinkets and Curio.
I will check later why the Chestslot isn't working as intended.

**Comment by Stein-N** [comment]
I tested the Chest slot and it worked without any issues. 
But with the next version the Backpack can be opened again when they are in the Inventory or eventually there will be another way.

**Comment by ayrus02** [comment]
Hi @Stein-N,  I can confirm that the Chest Slot KeyBind worked as intended, it is my fault that I change the KeyBind with other key to test it and I forgot.

So I will close this Issue.

Thanks for your time and effort making this mods.

Regards,
ayrus02

**Comment by ayrus02** [comment]
Closed
