### ISSUE TITLE
Resource Backpacks Returns Exit Code 1 When Trying to Launch on Quilt, MC version 1.21

### ISSUE THREAD

**Issue by susdra** [Stein-N/Resource-Backpacks#7]
See title. I don't know if the mod isn't supposed to be tagged for 1.21 or if there's some other issue, but I'd really like to use it as it's the only backpack mod on quilt for 1.21 right now

![image](https://github.com/user-attachments/assets/44a36da8-1828-450e-8090-0c4e3463c9eb)

**Comment by Stein-N** [comment]
Hey sorry for the late response, i didn't get any notification about this issue.

Like the error code says you have to download [Resource Config API](https://www.curseforge.com/minecraft/mc-mods/resource-config-api), also make sure that you have installed the latest version of [Resource Library](https://www.curseforge.com/minecraft/mc-mods/resource-library)

Please let me know if there are further issues.

**Comment by susdra** [comment]
Now I feel a bit silly, but it did work thanks! The problem was that when I downloaded Resource Backpacks from CurseForge, it installed Resource Library automatically, but not Resource Config API, so I didn't know there was a second dependency I needed. If its possible, maybe consider having it install both automatically. Thanks!

**Comment by Stein-N** [comment]
I tested it with Prism and the Curseforge Launcher and it downloads all dependencies correctly. But who knows what happend and it works now so no problem anymore :)
