### ISSUE TITLE
Resource Backpack missing all it's content when upgrading using Crafting Table.

### ISSUE THREAD

**Issue by ayrus02** [Stein-N/Resource-Backpacks#8]
Hi, 

Again, I'm reporting some mod's behavior that I've encountered. 
Last night I upgraded my Leather Backpack to a Copper Backpack, and the item inside the Leather Backpack is gone. 

![image](https://github.com/user-attachments/assets/c8f81257-8328-43f7-b84d-f4313b9137a9)
**Before Upgrading**

![image](https://github.com/user-attachments/assets/16e63253-7627-4dc7-b3ea-7484b7a56394)
**Being Upgraded**

![image](https://github.com/user-attachments/assets/75d514f8-6f58-4ecc-9287-ebebcc573c56)
**After Upgrading**

Is this intended behavior?

I've lost many items on the upgrade for the other backpack before. Please make the backpacks keep the inventory when upgraded, it's pretty bothering to empty the backpack first before upgrading it.

Regards,
ayrus02

**Comment by Stein-N** [comment]
I will have a look, when i'm back home.

**Comment by Stein-N** [comment]
Issue is fixed, but the version will be published later that day

**Comment by Stein-N** [comment]
New Version is available on Modrinth

**Comment by ayrus02** [comment]
Hi @Stein-N,

Thank you for your fast response and time devoted to this mod, but I'm currently using CurseForge. Could you also upload it to CurseForge beside Modrinth?

and what is the latest version number for this mod? Is it v0.6.1-BETA?? because it is the only version I can find on CurseForge and Modrinth... FYI, I use Fabric for my game platform. 

![image](https://github.com/user-attachments/assets/44cb0bd2-3674-4e9c-938a-5dd139fd186f)

![image](https://github.com/user-attachments/assets/19b8c74e-d435-4d13-b3fc-cb353a74fb09)


Regards,
ayrus02

**Comment by Stein-N** [comment]
im currently fixing an issue with trinkets, when this is fixed the version 0.6.2-BETA will be uploaded to curseforge and modrinth.

**Comment by Stein-N** [comment]
New Version is uploaded, will be available in 10-15 min on Curseforge

**Comment by ayrus02** [comment]
Hi @Stein-N,

I Can confirm the result of the update as below:

![image](https://github.com/user-attachments/assets/926a9c51-f36a-4025-9423-872714367886)
**Before Upgrade**

![image](https://github.com/user-attachments/assets/b2d36a92-726a-4a99-a54d-90082d53c095)
**Upgrading Backpack**

![image](https://github.com/user-attachments/assets/a3142e7c-d0f2-4b6b-9a74-31841457f9d9)
**After Upgrade**

It now retains the inventory of backpacks on upgrade.

Regards,
ayrus02
