### ISSUE TITLE
Multiple Backpacks can be opened at the same time

### ISSUE THREAD

**Issue by Nabhajit2005** [Stein-N/Resource-Backpacks#9]
Multiple backpacks present in the inventory can be opened at the same time. This is an overpowered feature, as it acts as shulker boxes but in a far superior way(you can right click to open instead of placing it down).

Players should only be able to use & open a single backpack when present in their inventory(or back slot). They can carry other backpacks but those should be empty. If this sounds unappealing, allows backpacks to be placed down using models(but cannot be placed in chests/barrels, due to the same reason for shulker boxes). That way players can have multiple backpacks with preset items for different purposes(tool backpack for mining, potion backpack for exploring, etc), but avoiding unbalanced gameplay.

**Comment by Nabhajit2005** [comment]
Btw i love the config feature which allows you to edit backpack storage space

**Comment by Stein-N** [comment]
Hey i'm currently working on the "Feature" to place all Backpacks, but it is not near finished yet.

The feature to open any Backpack from the Inventory via right-click is intentionally and i don't know about any other Backpack Mod that prevents the use of more than one Backpack in your inventory. If there is such a Mod please correct me.

The only thing i need to reconsider is the ability to open non equipped Backpacks via the Keybind.

Also in the final Release version all Backpacks will have an hardcoded maximum of rows/columns for every tier to have a base balancing.

**Comment by Lumb3rSamur4i** [comment]
I agree with the idea cause i find it kinda op for a starter storage option

**Comment by Stein-N** [comment]
With version 0.9.0-BETA there are the following changes:
- Backpacks can only be opened when placed like shulker boxes, but through the config you can enable opening backpacks from inventory
- Backpacks can only be opened via KeyBind when equipped in the Chest Slot
- no compatibility with any Trinket API
